version: 2
jobs:
  staging:
    docker:
      - image: circleci/node:lts
        environment:
          TZ: "Europe/London"
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: pull wmfs/node
          command: docker build -t test .
      - run:
          name: update package.json
          command: |
            sudo npm install -g npm-check-updates
            ncu -u
      - persist_to_workspace:
          root: .
          paths:
            - package.json
  test workspace:
    docker:
      - image: circleci/node:lts
        environment:
          TZ: "Europe/London"
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run:
          name: show package.json
          command: cat package.json
  uat_approval:
    docker:
      - image: circleci/node:lts
        environment:
          TZ: "Europe/London"
    working_directory: ~/repo
    steps:
      - checkout
  prod:
    docker:
      - image: circleci/node:lts
        environment:
          TZ: "Europe/London"
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: prod build
          command: docker build -t prod .
workflows:
  version: 2
  release-branch-workflow:
    jobs:
      - staging
      - test workspace:
          requires:
            - staging
      - uat_approval:
          type: approval
          requires:
            - test workspace
      - prod:
          requires:
            - uat_approval
