version: 2
jobs:
  staging:
    docker:
      - image: circleci/node:lts
        environment:
          TZ: "Europe/London"
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: vulnerability-db
      - run:
          name: pull wmfs/node
          command: docker build -t test .
  approval:
    docker:
      - image: circleci/node:lts
        environment:
          TZ: "Europe/London"
    working_direcotry: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: pull node-alpine
          command: docker tag test test:approved

workflows:
  version: 2
  release-branch-workflow:
    jobs:
      - staging
      - approval:
          type: approval
          requires:
            - staging
