version: 2.1
orbs:
  slack: circleci/slack@3.4.2
jobs:
  staging:
    docker:
      - image: circleci/node:lts
        environment:
          TZ: "Europe/London"
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: pull wmfs/node
          command: docker build -t test .
      - run:
          name: update package.json
          command: |
            sudo npm install -g npm-check-updates
            ncu -u
      - run:
          name: Store dev api Docker image
          command: docker save -o image.tar test
      - persist_to_workspace:
          root: .
          paths:
            - package.json
            - image.tar
  test workspace:
    docker:
      - image: circleci/node:lts
        environment:
          TZ: "Europe/London"
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: move package.json
          command: mv /tmp/workspace/package.json .
      - run:
          name: Load stored Docker image
          command: |
            docker load -i /tmp/workspace/image.tar
      - run:
          name: list images
          command: docker image ls
  test:
    docker:
      - image: circleci/node:lts
        environment:
          TZ: "Europe/London"
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          command: exit 1
      - slack/status:
          mentions: 'UAB9DNB9U'
          fail_only: true
          failure_message: Oh noes it's failed!
  prod:
    docker:
      - image: circleci/node:lts
        environment:
          TZ: "Europe/London"
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: prod build
          command: docker build -t prod .
      - slack/notify:
          color: '#42e2f4'
          mentions: 'UAB9DNB9U'
          message: It's worked
workflows:
  version: 2
  release-branch-workflow:
    jobs:
      - staging
      - test workspace:
          requires:
            - staging
      - test:
          requires:
            - test workspace
      - prod:
          requires:
            - test
