version: 2
jobs:
  staging:
    docker:
      - image: circleci/node:lts
        environment:
          TZ: "Europe/London"
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: pull wmfs/node
          command: docker build -t test .
  uat_approval:
    docker:
      - image: circleci/node:lts
        environment:
          TZ: "Europe/London"
    working_directory: ~/repo
    steps:
      - checkout
  prod:
    docker:
      - image: circleci/node:lts
        environment:
          TZ: "Europe/London"
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: prod build
          command: docker build -t prod .
workflows:
  version: 2
  release-branch-workflow:
    jobs:
      - staging
      - uat_approval:
          type: approval
          requires:
            - staging
      - prod:
          requires:
            - uat approval
